### ISSUE TITLE
Importing multiple sims3packs at once

### ISSUE THREAD

**Issue by Spleens1** [marcos4503/ts3-dream-launcher#1]
Hi.
I started switching to your launcher and am currently installing all my mods. But I also have a ton of sims3packs (furtnite, clothing etc.) installed. I don't see any option to install them all at once by selecting mutliple files. Is that not possible? I'm not gonna install ~300 files one-by-one per hand... 
I've already seen the Sim3Pack multi installer but according to you I am not allowed to manually install stuff inside my mods folder anymore.. So what do I do with them then?

**Comment by marcos4503** [comment]
Hey! Could you please re-post your issue on the Dream Launcher page, on Nexus Mods? For me, it's easier for everything to be concentrated in one place, so I can manage everything better! :)

You can use the "Forum" tab if you prefer :)
