### ISSUE TITLE
Claims that it isn't in the right directory, even after moving it to "Game\Bin"

### ISSUE THREAD

**Issue by NotLeafBoi** [marcos4503/ts3-dream-launcher#3]
![image_2024-07-19_124240118](https://github.com/user-attachments/assets/f9f1b4b9-ee9e-4395-8d92-9b21ba1f5266)
![image](https://github.com/user-attachments/assets/84c27d32-3186-4350-906d-18b1735f2bdf)

**Comment by marcos4503** [comment]
Hey! Was your copy of The Sims 3 provided by Steam? Downloaded and installed through Steam?

**Comment by marcos4503** [comment]
I see. Unfortunately Dream Launcher only supports the Steam version, as at least at the moment, I don't have enough time and I don't have the DVD or EA/Origin copies to support them.
