### ISSUE TITLE
Erro: "Launcher não colocado no diretório do jogo"

### ISSUE THREAD

**Issue by laurag1810** [marcos4503/ts3-dream-launcher#7]
![1 ](https://github.com/user-attachments/assets/51daef1f-5b74-4645-957d-25a10153ba6a)

ola, aparece esse erro
ja refiz 3x e nao resolve

**Comment by marcos4503** [comment]
Oi!

Qual é a versão do seu jogo? Ela é Pirata, Steam ou EA App/Origin?

**Comment by laurag1810** [comment]
oi! eu fiz na ea e na steam. na ea nao funcionou e na stem funcionou no dia q instalei. no dia seguinte o jogo ja nao abria, aparecia "verificando requisitos" e a tela ficava branca e saia do jogo.

**Comment by marcos4503** [comment]
É preciso ter em mente que o Launcher só é compatível com a versão da Steam. Dito isso, é algo realmente bem estranho...

Você chegou a modificar qualquer arquivo após ter o The Sims 3 e o Launcher instalado?

Há algum anti-virus ou outro programa de proteção/scan ativo no seu computador, que possa interferir nisso? Se houver um anti-virus ou qualquer coisa similar, tente desliga-lo, repetir o processo de instalação e checar se tudo está funcionando conforme o esperado.

Se após a instalação do Launcher, tudo funcionou, então deve sempre funcionar. Acredito que algo possa estar modificando a instalação do seu The Sims 3.

**Comment by laurag1810** [comment]
eu reinstalei e aconteceu o mesmo, funciona mas ao fecha-lo e reabrir ele nao funciona. nao modifiquei nenhum arquivo e nao sei como ver sobre o antivirus. vou investigar nelhor sobre

**Comment by marcos4503** [comment]
Tudo bem!
