### ISSUE TITLE
'Error: Update Error' when updating to Dream Launcher 1.40

### ISSUE THREAD

**Issue by JoRulez** [marcos4503/ts3-dream-launcher#8]
When trying to update to version 1.40 of Dream Launcher, after 'Stopping Processes', I receive the following:

![image](https://github.com/user-attachments/assets/950d4062-fcf3-4b90-b11b-30fa903ea5ef)

**Comment by marcos4503** [comment]
Please check if there is a file named "error-log.txt" in the "MyDocuments/Electronic Arts/The Sims 3/!DL-TmpCache/launcher-updater" directory. If this file exists, it should contain information about the error. Please post it here if it exists!
